export const SET_BALANCE = 'Wallet/SET_BALANCE'
export const SET_MARKET_PRICE = 'Wallet/SET_MARKET_PRICE'
export const RESET_PRICE = 'Wallet/RESET_PRICE'
export const SET_TRANSACTION_HISTORY = 'Wallet/SET_TRANSACTION_HISTORY'
